### ISSUE TITLE
Touch controls (swipe)

### ISSUE THREAD

**Issue by Bearphills** [littlekenny21/Escapig#2]
Can only swipe to the right when playing on android device

**Comment by imkingping** [comment]
is this in the most recent master (V.0.22)?, just an update also, got health and fall back on hit working, encountered an issue where pig seems to take the corner too early, i think it might be if you change lane when entering the corner, either way i'm working on that now, don't know how to use smartgit to upload or push or whatever.

**Comment by Bearphills** [comment]
Yeah it is in the most recent
